# Generated by Django 2.2 on 2019-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('country', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'scoreboard',
                'ordering': ['score'],
            },
        ),
    ]
